//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 TriggerMesh Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]Parameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentFormFactor) DeepCopyInto(out *DeploymentFormFactor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentFormFactor.
func (in *DeploymentFormFactor) DeepCopy() *DeploymentFormFactor {
	if in == nil {
		return nil
	}
	out := new(DeploymentFormFactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormFactor) DeepCopyInto(out *FormFactor) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeploymentFormFactor)
		**out = **in
	}
	if in.KnativeService != nil {
		in, out := &in.KnativeService, &out.KnativeService
		*out = new(KnativeServiceFormFactor)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormFactor.
func (in *FormFactor) DeepCopy() *FormFactor {
	if in == nil {
		return nil
	}
	out := new(FormFactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateDecoration) DeepCopyInto(out *GenerateDecoration) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateDecoration.
func (in *GenerateDecoration) DeepCopy() *GenerateDecoration {
	if in == nil {
		return nil
	}
	out := new(GenerateDecoration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateNames) DeepCopyInto(out *GenerateNames) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateNames.
func (in *GenerateNames) DeepCopy() *GenerateNames {
	if in == nil {
		return nil
	}
	out := new(GenerateNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateVersion) DeepCopyInto(out *GenerateVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateVersion.
func (in *GenerateVersion) DeepCopy() *GenerateVersion {
	if in == nil {
		return nil
	}
	out := new(GenerateVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeServiceFormFactor) DeepCopyInto(out *KnativeServiceFormFactor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeServiceFormFactor.
func (in *KnativeServiceFormFactor) DeepCopy() *KnativeServiceFormFactor {
	if in == nil {
		return nil
	}
	out := new(KnativeServiceFormFactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Section != nil {
		in, out := &in.Section, &out.Section
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ParameterSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterOptions) DeepCopyInto(out *ParameterOptions) {
	*out = *in
	if in.ArbitraryParameters != nil {
		in, out := &in.ArbitraryParameters, &out.ArbitraryParameters
		*out = new(bool)
		**out = **in
	}
	if in.KeyCasing != nil {
		in, out := &in.KeyCasing, &out.KeyCasing
		*out = new(KeyCasing)
		**out = **in
	}
	if in.KeyStyle != nil {
		in, out := &in.KeyStyle, &out.KeyStyle
		*out = new(KeyStyle)
		**out = **in
	}
	if in.KeyPrefix != nil {
		in, out := &in.KeyPrefix, &out.KeyPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterOptions.
func (in *ParameterOptions) DeepCopy() *ParameterOptions {
	if in == nil {
		return nil
	}
	out := new(ParameterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSource) DeepCopyInto(out *ParameterSource) {
	*out = *in
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(v1.ObjectFieldSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSource.
func (in *ParameterSource) DeepCopy() *ParameterSource {
	if in == nil {
		return nil
	}
	out := new(ParameterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrationFromImage) DeepCopyInto(out *RegistrationFromImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrationFromImage.
func (in *RegistrationFromImage) DeepCopy() *RegistrationFromImage {
	if in == nil {
		return nil
	}
	out := new(RegistrationFromImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workload) DeepCopyInto(out *Workload) {
	*out = *in
	in.FormFactor.DeepCopyInto(&out.FormFactor)
	out.FromImage = in.FromImage
	if in.ParameterOptions != nil {
		in, out := &in.ParameterOptions, &out.ParameterOptions
		*out = new(ParameterOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in *Workload) DeepCopy() *Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return out
}
