//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 TriggerMesh Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/triggermesh/scoby/pkg/apis/scoby.triggermesh.io/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRegistration) DeepCopyInto(out *GenericRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRegistration.
func (in *GenericRegistration) DeepCopy() *GenericRegistration {
	if in == nil {
		return nil
	}
	out := new(GenericRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRegistrationGenerate) DeepCopyInto(out *GenericRegistrationGenerate) {
	*out = *in
	in.Names.DeepCopyInto(&out.Names)
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(common.GenerateVersion)
		**out = **in
	}
	in.GenerateDecoration.DeepCopyInto(&out.GenerateDecoration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRegistrationGenerate.
func (in *GenericRegistrationGenerate) DeepCopy() *GenericRegistrationGenerate {
	if in == nil {
		return nil
	}
	out := new(GenericRegistrationGenerate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRegistrationList) DeepCopyInto(out *GenericRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenericRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRegistrationList.
func (in *GenericRegistrationList) DeepCopy() *GenericRegistrationList {
	if in == nil {
		return nil
	}
	out := new(GenericRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRegistrationSpec) DeepCopyInto(out *GenericRegistrationSpec) {
	*out = *in
	in.Generate.DeepCopyInto(&out.Generate)
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRegistrationSpec.
func (in *GenericRegistrationSpec) DeepCopy() *GenericRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(GenericRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRegistrationStatus) DeepCopyInto(out *GenericRegistrationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRegistrationStatus.
func (in *GenericRegistrationStatus) DeepCopy() *GenericRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(GenericRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}
