//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 TriggerMesh Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	"k8s.io/api/core/v1"
	"knative.dev/pkg/apis"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(apis.URL)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Address.
func (in *Address) DeepCopy() *Address {
	if in == nil {
		return nil
	}
	out := new(Address)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltInfunction) DeepCopyInto(out *BuiltInfunction) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltInfunction.
func (in *BuiltInfunction) DeepCopy() *BuiltInfunction {
	if in == nil {
		return nil
	}
	out := new(BuiltInfunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsFromHook) DeepCopyInto(out *ConditionsFromHook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsFromHook.
func (in *ConditionsFromHook) DeepCopy() *ConditionsFromHook {
	if in == nil {
		return nil
	}
	out := new(ConditionsFromHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizeParameterConfiguration) DeepCopyInto(out *CustomizeParameterConfiguration) {
	*out = *in
	if in.Render != nil {
		in, out := &in.Render, &out.Render
		*out = new(ParameterRenderConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizeParameterConfiguration.
func (in *CustomizeParameterConfiguration) DeepCopy() *CustomizeParameterConfiguration {
	if in == nil {
		return nil
	}
	out := new(CustomizeParameterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentFormFactor) DeepCopyInto(out *DeploymentFormFactor) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(DeploymentService)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentFormFactor.
func (in *DeploymentFormFactor) DeepCopy() *DeploymentFormFactor {
	if in == nil {
		return nil
	}
	out := new(DeploymentFormFactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentService) DeepCopyInto(out *DeploymentService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentService.
func (in *DeploymentService) DeepCopy() *DeploymentService {
	if in == nil {
		return nil
	}
	out := new(DeploymentService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormFactor) DeepCopyInto(out *FormFactor) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeploymentFormFactor)
		(*in).DeepCopyInto(*out)
	}
	if in.KnativeService != nil {
		in, out := &in.KnativeService, &out.KnativeService
		*out = new(KnativeServiceFormFactor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormFactor.
func (in *FormFactor) DeepCopy() *FormFactor {
	if in == nil {
		return nil
	}
	out := new(FormFactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalParameterConfiguration) DeepCopyInto(out *GlobalParameterConfiguration) {
	*out = *in
	if in.DefaultPrefix != nil {
		in, out := &in.DefaultPrefix, &out.DefaultPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalParameterConfiguration.
func (in *GlobalParameterConfiguration) DeepCopy() *GlobalParameterConfiguration {
	if in == nil {
		return nil
	}
	out := new(GlobalParameterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hook) DeepCopyInto(out *Hook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hook.
func (in *Hook) DeepCopy() *Hook {
	if in == nil {
		return nil
	}
	out := new(Hook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookServiceConfiguration) DeepCopyInto(out *HookServiceConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookServiceConfiguration.
func (in *HookServiceConfiguration) DeepCopy() *HookServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(HookServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeServiceFormFactor) DeepCopyInto(out *KnativeServiceFormFactor) {
	*out = *in
	if in.MinScale != nil {
		in, out := &in.MinScale, &out.MinScale
		*out = new(int)
		**out = **in
	}
	if in.MaxScale != nil {
		in, out := &in.MaxScale, &out.MaxScale
		*out = new(int)
		**out = **in
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeServiceFormFactor.
func (in *KnativeServiceFormFactor) DeepCopy() *KnativeServiceFormFactor {
	if in == nil {
		return nil
	}
	out := new(KnativeServiceFormFactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
	if in.Skip != nil {
		in, out := &in.Skip, &out.Skip
		*out = new(bool)
		**out = **in
	}
	if in.Render != nil {
		in, out := &in.Render, &out.Render
		*out = new(ParameterRender)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterConfiguration) DeepCopyInto(out *ParameterConfiguration) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalParameterConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.AddEnvs != nil {
		in, out := &in.AddEnvs, &out.AddEnvs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Customize != nil {
		in, out := &in.Customize, &out.Customize
		*out = make([]CustomizeParameterConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterConfiguration.
func (in *ParameterConfiguration) DeepCopy() *ParameterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ParameterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterRender) DeepCopyInto(out *ParameterRender) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterRender.
func (in *ParameterRender) DeepCopy() *ParameterRender {
	if in == nil {
		return nil
	}
	out := new(ParameterRender)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterRenderConfiguration) DeepCopyInto(out *ParameterRenderConfiguration) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFromConfigMap != nil {
		in, out := &in.ValueFromConfigMap, &out.ValueFromConfigMap
		*out = new(ObjectReference)
		**out = **in
	}
	if in.ValueFromSecret != nil {
		in, out := &in.ValueFromSecret, &out.ValueFromSecret
		*out = new(ObjectReference)
		**out = **in
	}
	if in.ValueFromBuiltInFunc != nil {
		in, out := &in.ValueFromBuiltInFunc, &out.ValueFromBuiltInFunc
		*out = new(BuiltInfunction)
		(*in).DeepCopyInto(*out)
	}
	if in.Skip != nil {
		in, out := &in.Skip, &out.Skip
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterRenderConfiguration.
func (in *ParameterRenderConfiguration) DeepCopy() *ParameterRenderConfiguration {
	if in == nil {
		return nil
	}
	out := new(ParameterRenderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSource) DeepCopyInto(out *ParameterSource) {
	*out = *in
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(v1.ObjectFieldSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSource.
func (in *ParameterSource) DeepCopy() *ParameterSource {
	if in == nil {
		return nil
	}
	out := new(ParameterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reference) DeepCopyInto(out *Reference) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(HookServiceConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Finalization != nil {
		in, out := &in.Finalization, &out.Finalization
		*out = new(HookServiceConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reference.
func (in *Reference) DeepCopy() *Reference {
	if in == nil {
		return nil
	}
	out := new(Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrationFromImage) DeepCopyInto(out *RegistrationFromImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrationFromImage.
func (in *RegistrationFromImage) DeepCopy() *RegistrationFromImage {
	if in == nil {
		return nil
	}
	out := new(RegistrationFromImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusAddElement) DeepCopyInto(out *StatusAddElement) {
	*out = *in
	if in.Render != nil {
		in, out := &in.Render, &out.Render
		*out = new(StatusRenderConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusAddElement.
func (in *StatusAddElement) DeepCopy() *StatusAddElement {
	if in == nil {
		return nil
	}
	out := new(StatusAddElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusConfiguration) DeepCopyInto(out *StatusConfiguration) {
	*out = *in
	if in.AddElements != nil {
		in, out := &in.AddElements, &out.AddElements
		*out = make([]StatusAddElement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConditionsFromHook != nil {
		in, out := &in.ConditionsFromHook, &out.ConditionsFromHook
		*out = make([]ConditionsFromHook, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusConfiguration.
func (in *StatusConfiguration) DeepCopy() *StatusConfiguration {
	if in == nil {
		return nil
	}
	out := new(StatusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusRenderConfiguration) DeepCopyInto(out *StatusRenderConfiguration) {
	*out = *in
	if in.ValueFromParameter != nil {
		in, out := &in.ValueFromParameter, &out.ValueFromParameter
		*out = new(StatusValueFromParameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusRenderConfiguration.
func (in *StatusRenderConfiguration) DeepCopy() *StatusRenderConfiguration {
	if in == nil {
		return nil
	}
	out := new(StatusRenderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusValueFromParameter) DeepCopyInto(out *StatusValueFromParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusValueFromParameter.
func (in *StatusValueFromParameter) DeepCopy() *StatusValueFromParameter {
	if in == nil {
		return nil
	}
	out := new(StatusValueFromParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workload) DeepCopyInto(out *Workload) {
	*out = *in
	if in.FormFactor != nil {
		in, out := &in.FormFactor, &out.FormFactor
		*out = new(FormFactor)
		(*in).DeepCopyInto(*out)
	}
	out.FromImage = in.FromImage
	if in.ParameterConfiguration != nil {
		in, out := &in.ParameterConfiguration, &out.ParameterConfiguration
		*out = new(ParameterConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusConfiguration != nil {
		in, out := &in.StatusConfiguration, &out.StatusConfiguration
		*out = new(StatusConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in *Workload) DeepCopy() *Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return out
}
